## **Exercice Numpy**

Voici une série de questions pour vous familiariser avec l'utilisation de la bibliothèque NumPy.

### **Pour aller plus loin**

Il existe un excellent entraînement collaboratif qui vous montrera de nombreuses facettes de NumPy. Ce GitHub, nommé "numpy-100", sera un excellent entraînement pour vous. Vous pouvez accéder au lien [ici](https://github.com/rougier/numpy-100).

---

#### **Création de tableaux**

**Question 1**  
Comment importez-vous la bibliothèque NumPy en Python ?

In [2]:
# Pour importer la bibliothèque NumPy en Python, vous pouvez utiliser l'instruction suivante :
import numpy as np


**Question 2**  
Comment créez-vous un tableau NumPy vide ?

In [3]:
# Pour créer un tableau NumPy vide, vous pouvez utiliser la fonction numpy.empty() de la manière suivante :
arr = np.empty(shape=(3, 3))  # Crée un tableau 3x3 vide
arr

array([[ 2.60605835e-31, -5.21211670e-31,  1.30302917e-31],
       [-5.21211670e-31,  1.13363538e-30, -3.51817877e-31],
       [ 1.30302917e-31, -3.51817877e-31,  2.01969522e-31]])

**Question 3**  
Comment créez-vous un tableau NumPy rempli de zéros ?

In [4]:
# Pour créer un tableau NumPy rempli de zéros, utilisez la fonction numpy.zeros() :

arr = np.zeros(shape=(4, 4))  # Crée un tableau 4x4 rempli de zéros
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Question 4**  
Comment créez-vous un tableau NumPy rempli de uns ?

In [5]:
# Pour créer un tableau NumPy rempli de uns, utilisez la fonction numpy.ones() :

arr = np.ones(shape=(2, 2))  # Crée un tableau 2x2 rempli de uns
arr

array([[1., 1.],
       [1., 1.]])

**Question 5**  
Comment créez-vous un tableau NumPy rempli d'une valeur spécifique, par exemple 7 ?

In [6]:
# Pour créer un tableau NumPy rempli d'une valeur spécifique, utilisez la fonction numpy.full() :
arr = np.full(shape=(3, 3), fill_value=7)  # Crée un tableau 3x3 rempli de la valeur 7

arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

**Question 6**  
Comment créez-vous un tableau NumPy à partir d'une liste Python existante ?

In [7]:
# Vous pouvez créer un tableau NumPy à partir d'une liste Python existante en utilisant la fonction numpy.array() :

my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)  # Crée un tableau NumPy à partir de my_list
arr

array([1, 2, 3, 4, 5])

**Question 7**  
Pouvez-vous créer un tableau NumPy de dimensions 3x3 rempli de zéros ?

In [8]:

arr = np.zeros((3, 3))  # Crée un tableau 3x3 rempli de zéros
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Question 8**  
Comment créez-vous un tableau NumPy de valeurs aléatoires entre 0 et 1 ?

In [9]:
# Pour créer un tableau NumPy de valeurs aléatoires entre 0 et 1, utilisez la fonction numpy.random.rand() :

arr = np.random.rand(3, 3)  # Crée un tableau 3x3 de valeurs aléatoires entre 0 et 1
arr

array([[0.17406893, 0.92316919, 0.72235354],
       [0.73640279, 0.21250012, 0.48529363],
       [0.26015115, 0.11409351, 0.96346349]])

**Question 9**  
Comment obtenir la forme (shape) d'un tableau NumPy ?


In [10]:
# Vous pouvez obtenir la forme d'un tableau NumPy en utilisant l'attribut .shape :

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape = arr.shape  # Cela renverra la forme (shape) du tableau, par exemple, (2, 3) pour un tableau 2x3.
shape

(2, 3)

---

#### Manipulation de tableaux


**Question 10**  
Comment obtenir le nombre de dimensions d'un tableau NumPy ?

In [11]:
# Vous pouvez obtenir le nombre de dimensions d'un tableau NumPy en utilisant l'attribut .ndim :

arr = np.array([[1, 2, 3], [4, 5, 6]])
dimensions = arr.ndim  # Cela renverra le nombre de dimensions, par exemple, 2 pour un tableau 2D.
dimensions

2

**Question 11**  
Comment obtenir le nombre total d'éléments dans un tableau NumPy ?

In [12]:
# Pour obtenir le nombre total d'éléments dans un tableau NumPy, utilisez l'attribut .size :

arr = np.array([[1, 2, 3], [4, 5, 6]])
total_elements = arr.size  # Cela renverra le nombre total d'éléments, par exemple, 6 pour un tableau 2x3.
total_elements

6

**Question 12**  
Comment accédez-vous à un élément spécifique dans un tableau NumPy ?

In [13]:
# Vous pouvez accéder à un élément spécifique dans un tableau NumPy en utilisant l'indexage :

arr = np.array([[1, 2, 3], [4, 5, 6]])
element = arr[0, 1]  # Cela renverra l'élément à la première ligne (index 0) et deuxième colonne (index 1), soit 2.


**Question 13**  
Comment extrayez-vous une tranche (slice) d'un tableau NumPy ?


In [14]:
# Vous pouvez extraire une tranche d'un tableau NumPy en utilisant l'indexage par tranche :

arr = np.array([1, 2, 3, 4, 5])
sliced_arr = arr[1:4]  # Cela renverra une tranche de l'index 1 à l'index 3, soit [2, 3, 4].
sliced_arr

array([2, 3, 4])

**Question 14**  
Comment effectuez-vous une opération d'addition entre deux tableaux NumPy ?

In [15]:
# Pour effectuer une opération d'addition entre deux tableaux NumPy, utilisez l'opérateur + :

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2  # Cela renverra un nouveau tableau avec l'addition élément par élément.
result

array([5, 7, 9])

**Question 15**  
Comment effectuez-vous une opération de multiplication entre deux tableaux NumPy ?

In [16]:
# Pour effectuer une opération de multiplication entre deux tableaux NumPy, utilisez l'opérateur * :

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2  # Cela renverra un nouveau tableau avec la multiplication élément par élément.
result

array([ 4, 10, 18])

**Question 16**  
Comment effectuez-vous une opération de multiplication entre un tableau NumPy et un scalaire ?

In [17]:
# Vous pouvez effectuer une opération de multiplication entre un tableau NumPy et un scalaire directement :

arr = np.array([1, 2, 3])
result = arr * 5  # Cela renverra un nouveau tableau avec chaque élément multiplié par 5.
result

array([ 5, 10, 15])

**Question 17**  
Comment trouvez-vous la valeur maximale dans un tableau NumPy ?

In [18]:
# Pour trouver la valeur maximale dans un tableau NumPy, utilisez la fonction numpy.max() :

arr = np.array([4, 2, 9, 7, 5])
max_value = np.max(arr)  # Cela renverra la valeur maximale dans le tableau, soit 9.
max_value

9

**Question 18**  
Comment trouvez-vous la valeur minimale dans un tableau NumPy ?

In [19]:
# Pour trouver la valeur minimale dans un tableau NumPy, utilisez la fonction numpy.min() :

arr = np.array([4, 2, 9, 7, 5])
min_value = np.min(arr)  # Cela renverra la valeur minimale dans le tableau, soit 2.
min_value

2

**Question 19**  
Comment trouvez-vous la somme des éléments d'un tableau NumPy ?

In [20]:
# Pour trouver la somme des éléments d'un tableau NumPy, utilisez la fonction numpy.sum() :

arr = np.array([1, 2, 3, 4, 5])
sum_value = np.sum(arr)  # Cela renverra la somme des éléments, soit 15.
sum_value

15

**Question 20**  
Comment trouvez-vous la moyenne des éléments d'un tableau NumPy ?

In [21]:
# Pour trouver la moyenne des éléments d'un tableau NumPy, utilisez la fonction numpy.mean() :

arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)  # Cela renverra la moyenne des éléments, soit 3.0.
mean_value

3.0

---

#### **Filtrage et indexation avancés**

**Question 21**  
Comment sélectionnez-vous toutes les valeurs supérieures à 5 dans un tableau NumPy ?

In [22]:
# Vous pouvez sélectionner toutes les valeurs supérieures à 5 dans un tableau NumPy avec une condition booléenne :

arr = np.array([3, 8, 1, 6, 9])
selected_values = arr[arr > 5]  # Cela renverra un tableau avec les valeurs supérieures à 5.
selected_values

array([8, 6, 9])

**Question 22**  
Comment sélectionnez-vous toutes les valeurs d'un tableau NumPy qui sont égales à une valeur spécifique, par exemple 3 ?


In [23]:
# Vous pouvez sélectionner toutes les valeurs égales à 3 dans un tableau NumPy avec une condition booléenne :

arr = np.array([3, 8, 1, 3, 6])
selected_values = arr[arr == 3]  # Cela renverra un tableau avec les valeurs égales à 3.
selected_values

array([3, 3])

**Question 23**  
Comment obtenez-vous les indices des valeurs supérieures à 10 dans un tableau NumPy ?

In [28]:
# Pour obtenir les indices des valeurs supérieures à 10 dans un tableau NumPy, utilisez la fonction numpy.where() :

arr = np.array([5, 15, 2, 12, 8])
indices = np.where(arr > 10)  # Cela renverra un tableau d'indices où les valeurs sont supérieures à 10.
print(indices)

# On peut aussi changer les valeurs d'un tableau NumPy en utilisantnp.where() :
arr1 = np.where(arr > 10, 0, arr)  # Cela renverra un tableau avec les valeurs supérieures à 10 remplacées par 0 .
arr1

(array([1, 3]),)


array([5, 0, 2, 0, 8])

**Question 24**  
Comment changez-vous la valeur de tous les éléments d'un tableau NumPy qui sont inférieurs à 0 par 0 ?

In [ ]:
# Vous pouvez changer la valeur des éléments inférieurs à 0 à 0 en utilisant une condition booléenne :

arr = np.array([1, -2, 3, -4, 5])
arr[arr < 0] = 0  # Cela mettra à zéro tous les éléments négatifs dans le tableau.
arr

**Question 25**  
Comment obtenez-vous un nouveau tableau NumPy contenant uniquement les éléments uniques d'un tableau existant ?

In [ ]:
# Pour obtenir un nouveau tableau NumPy avec des éléments uniques, utilisez la fonction numpy.unique() :
arr = np.array([1, 2, 2, 3, 3, 4, 4, 5])
unique_values = np.unique(arr)  # Cela renverra un tableau avec les éléments uniques, [1, 2, 3, 4, 5].
unique_values

---

#### **Opérations mathématiques**

**Question 26**  
Comment effectuez-vous une opération puissance sur tous les éléments d'un tableau NumPy ?


In [ ]:
# Pour effectuer une opération d'exponentiation sur tous les éléments d'un tableau NumPy, utilisez la fonction numpy.power() :

arr = np.array([2, 3, 4])
exponentiated_arr = np.power(arr, 2)  # Élève chaque élément au carré.
exponentiated_arr

**Question 27**  
Comment effectuez-vous une opération de racine carrée sur tous les éléments d'un tableau NumPy ?

In [ ]:
# Vous pouvez effectuer une opération de racine carrée sur tous les éléments d'un tableau NumPy en utilisant la fonction numpy.sqrt() :

arr = np.array([4, 9, 16])
sqrt_arr = np.sqrt(arr)  # Cela renverra la racine carrée de chaque élément.
sqrt_arr

**Question 28**  
Comment effectuez-vous une opération de calcul logarithmique sur tous les éléments d'un tableau NumPy ?

In [ ]:
# Pour effectuer une opération de calcul logarithmique sur tous les éléments d'un tableau NumPy, utilisez la fonction numpy.log() :

arr = np.array([1, 10, 100])
log_arr = np.log(arr)  # Cela renverra le logarithme naturel de chaque élément.
log_arr

**Question 29**  
Comment effectuez-vous une opération de calcul de la moyenne mobile sur un tableau NumPy ?

In [ ]:
# Pour effectuer une opération de calcul de la moyenne mobile sur un tableau NumPy, vous pouvez utiliser la fonction numpy.convolve() :

arr = np.array([1, 2, 3, 4, 5])
window = np.array([0.25, 0.5, 0.25])  # Fenêtre de moyenne mobile
result = np.convolve(arr, window, mode='valid')  # Calcule la moyenne mobile sur le tableau.
result

**Question 30**  
Comment arrondissez-vous tous les éléments d'un tableau NumPy à deux décimales ?


In [ ]:
# Vous pouvez arrondir tous les éléments d'un tableau NumPy à deux décimales en utilisant la fonction numpy.round() :

arr = np.array([1.2345, 2.5678, 3.7890])
rounded_arr = np.round(arr, decimals=2)  # Cela renverra un tableau avec des éléments arrondis à deux décimales.
rounded_arr

---

#### **Combinaison de tableaux**

**Question 31**  
Comment concaténez-vous deux tableaux NumPy horizontalement (côte à côte) ?

In [ ]:
# Pour concaténer deux tableaux NumPy horizontalement, utilisez la fonction numpy.hstack() :

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.hstack((arr1, arr2))  # Concatène les deux tableaux horizontalement.
concatenated_arr

**Question 32**  
Comment concaténez-vous deux tableaux NumPy verticalement (l'un au-dessus de l'autre) ?

In [ ]:
# Pour concaténer deux tableaux NumPy verticalement, utilisez la fonction numpy.vstack() :

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.vstack((arr1, arr2))  # Concatène les deux tableaux verticalement.
concatenated_arr

**Question 33**  
Comment fusionnez-vous deux tableaux NumPy en supprimant les doublons ?

In [ ]:
# Pour fusionner deux tableaux NumPy en supprimant les doublons, utilisez la fonction numpy.union1d() :

arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 4, 5])
merged_arr = np.union1d(arr1, arr2)  # Fusionne les tableaux en supprimant les doublons.
merged_arr

**Question 34**  
Comment effectuez-vous une concatenation de deux tableaux NumPy ?

In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))  # Concatène les deux tableaux verticalement.
concatenated_arr

array([1, 2, 3, 4, 5, 6])

#### **Statistiques descriptives**

**Question 35**  
Comment calculez-vous l'écart type d'un tableau NumPy ?


In [ ]:
# Pour calculer l'écart type d'un tableau NumPy, utilisez la fonction numpy.std() :

arr = np.array([2, 4, 6, 8, 10])
std_deviation = np.std(arr)  # Cela renverra l'écart type du tableau.


**Question 36**  
Comment calculez-vous la médiane d'un tableau NumPy ?

In [ ]:
# Pour calculer la médiane d'un tableau NumPy, utilisez la fonction numpy.median() :

arr = np.array([5, 2, 8, 1, 7])
median_value = np.median(arr)  # Cela renverra la médiane du tableau.
median_value

**Question 37**  
Comment calculez-vous la variance d'un tableau NumPy ?


In [ ]:
# Pour calculer la variance d'un tableau NumPy, utilisez la fonction numpy.var() :

arr = np.array([2, 4, 6, 8, 10])
variance = np.var(arr)  # Cela renverra la variance du tableau.


**Question 38**  
Comment calculez-vous la corrélation entre deux tableaux NumPy ?


In [ ]:
# Pour calculer la corrélation entre deux tableaux NumPy, utilisez la fonction numpy.corrcoef() :

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
correlation = np.corrcoef(arr1, arr2)  # Cela renverra la matrice de corrélation entre les deux tableaux.


#### **Sauvegarde et chargement de tableaux**

**Question 39**  
Comment sauvegardez-vous un tableau NumPy dans un fichier ?


In [ ]:
# Pour sauvegarder un tableau NumPy dans un fichier, utilisez la fonction numpy.save() :

arr = np.array([1, 2, 3, 4, 5])
np.save('mon_tableau.npy', arr)  # Cela sauvegardera le tableau dans un fichier appelé "mon_tableau.npy".


**Question 40**  
Comment chargez-vous un tableau NumPy à partir d'un fichier ?

In [ ]:
# Pour charger un tableau NumPy à partir d'un fichier, utilisez la fonction numpy.load() :

loaded_arr = np.load('mon_tableau.npy')  # Cela chargera le tableau depuis le fichier "mon_tableau.npy".


#### **Manipulation avancée**

**Question 41**  
Comment inversez-vous l'ordre des éléments dans un tableau NumPy ?

In [31]:
# Vous pouvez inverser l'ordre des éléments dans un tableau NumPy en utilisant l'indexage inversé :
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]  # Cela renverra le tableau avec les éléments dans l'ordre inverse.
other = np.flip(arr)
reversed_arr,other

(array([5, 4, 3, 2, 1]), array([5, 4, 3, 2, 1]))

**Question 42**  
Comment transposerez-vous un tableau NumPy ?

In [ ]:
# Pour transposer un tableau NumPy, utilisez l'attribut .T :

arr = np.array([[1, 2], [3, 4]])
transposed_arr = arr.T  # Cela renverra le tableau transposé.


**Question 43**  
Comment redimensionnez-vous un tableau NumPy ?

In [ ]:
# Vous pouvez redimensionner un tableau NumPy en utilisant la fonction numpy.reshape() :

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Cela redimensionnera le tableau en une forme de 2x3.


**Question 44**  
Comment remplacez-vous toutes les valeurs NaN dans un tableau NumPy par une valeur spécifique ?

In [ ]:
# Pour remplacer toutes les valeurs NaN (Not a Number) dans un tableau NumPy par une valeur spécifique, utilisez la fonction numpy.nan_to_num() :

arr = np.array([1.0, np.nan, 2.0, np.nan, 3.0])
replaced_arr = np.nan_to_num(arr, nan=0.0)  # Cela remplacera les NaN par 0.0.


**Question 45**  
Comment supprimez-vous toutes les valeurs NaN d'un tableau NumPy ?


In [ ]:
# Pour supprimer toutes les valeurs NaN d'un tableau NumPy, utilisez la fonction numpy.isnan() et l'indexage booléen :

arr = np.array([1.0, np.nan, 2.0, np.nan, 3.0])
cleaned_arr = arr[~np.isnan(arr)]  # Cela supprimera les valeurs NaN du tableau.


**Question 46**  
Comment triez-vous un tableau NumPy par ordre croissant ?

In [ ]:
# Pour trier un tableau NumPy par ordre croissant, utilisez la fonction numpy.sort() :

arr = np.array([3, 1, 4, 2, 5])
sorted_arr = np.sort(arr)  # Cela renverra un nouveau tableau trié par ordre croissant.
sorted_arr

**Question 47**  
Comment triez-vous un tableau NumPy par ordre décroissant ?

In [ ]:
# Pour trier un tableau NumPy par ordre décroissant, utilisez la fonction numpy.sort() avec l'argument "kind='quicksort'" et inversez les indices :

arr = np.array([3, 1, 4, 2, 5])
sorted_arr = np.sort(arr)[::-1]  # Cela renverra un nouveau tableau trié par ordre décroissant.
sorted_arr

**Question 48**  
Comment effectuez-vous une opération de multiplication matricielle entre deux tableaux NumPy ?


In [ ]:
# Pour effectuer une opération de multiplication matricielle entre deux tableaux NumPy, utilisez la fonction numpy.dot() ou l'opérateur @ :

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2) # Cela renverra le produit matriciel des deux matrices.
print(result)
# Ou avec l'opérateur @
result = matrix1 @ matrix2
print(result)
# Ou avec la méthode matmul
result = np.matmul(matrix1, matrix2)
print(result)


**Question 49**  
Comment calculez-vous le produit scalaire entre deux tableaux NumPy ?

In [ ]:
# Pour calculer le produit scalaire entre deux tableaux NumPy, utilisez la fonction numpy.dot() :

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)  # Cela renverra le produit scalaire des deux tableaux.


**Question 50**  
Comment appliquez-vous une fonction personnalisée à chaque élément d'un tableau NumPy ?



In [ ]:
# Vous pouvez appliquer une fonction personnalisée à chaque élément d'un tableau NumPy en utilisant la fonction numpy.vectorize() :


# Définissez une fonction personnalisée
def custom_function(x):
    return x * 2

arr = np.array([1, 2, 3, 4, 5])

# Appliquez la fonction personnalisée à chaque élément du tableau
result = np.vectorize(custom_function)(arr)
